---
AWSTemplateFormatVersion: 2010-09-09
Description: Exportinator application stack (asg, elb, dns record)

Resources:
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::Select:
            - 0
            - Ref: ASGSubnets
        - Fn::Select:
            - 1
            - Ref: ASGSubnets
      LaunchConfigurationName:
        Ref: LaunchConfig
      MinSize: '1'
      MaxSize: '2'
      TargetGroupARNs:
        - Ref: ELBTG
      Tags:
        - Key: Name
          Value: exportinator
          PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType: t3.medium
      AssociatePublicIpAddress: true
      IamInstanceProfile:
        Ref: Profile
      SecurityGroups:
        - Ref: SGELB
      UserData:
        'Fn::Base64': |
          #!/bin/bash -ex
          /opt/exportinator/api/launch.sh

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: ASG
      Cooldown: '60'
      ScalingAdjustment: 1

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: ASG
      Cooldown: '60'
      ScalingAdjustment: -1

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 90% for 10 minutes
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      AlarmActions:
        - Ref: ScaleUpPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: ASG
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 70% for 10 minutes
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      AlarmActions:
        - Ref: ScaleDownPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: ASG
      ComparisonOperator: LessThanThreshold

  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - Ref: SGCorp
      Subnets:
        - Fn::Select:
            - 0
            - Ref: ELBSubnets
        - Fn::Select:
            - 1
            - Ref: ELBSubnets

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn:
            Ref: Cert
      DefaultActions:
        - TargetGroupArn:
            Ref: ELBTG
          Type: forward
      LoadBalancerArn:
        Ref: ELB
      Port: 443
      Protocol: HTTPS

  ELBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      HealthCheckPath: /health_check
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Ref: VPC

  Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: Role

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: HostedZoneId
      Comment: exportinator DNS name.
      Name:
        Ref: Domain
      Type: A
      AliasTarget:
        HostedZoneId:
          Fn::GetAtt: ELB.CanonicalHostedZoneID
        DNSName:
          Fn::GetAtt: ELB.DNSName
